[package]
name = "message_board"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
actix-web-httpauth = "0.8"
actix-rt = "2.9"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "mysql", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bcrypt = "0.15"
jsonwebtoken = "9.2"
tokio = { version = "1.35", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
env_logger = "0.11"
log = "0.4"

[dev-dependencies]
actix-rt = "2.9"
