[package]
name = "messageboard"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9"
actix-cors = "0.7"
sqlx = { version = "0.8", features = ["runtime-tokio-native-tls", "mysql", "chrono"] }
tokio = { version = "1.41", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
bcrypt = "0.15"
jsonwebtoken = "9.3"
dotenv = "0.15"
env_logger = "0.11"
log = "0.4"
thiserror = "2.0"
validator = { version = "0.18", features = ["derive"] }
uuid = { version = "1.11", features = ["v4", "serde"] }
futures-util = "0.3"
