version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: message-board-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-StrongRootPassword123!}
      MYSQL_DATABASE: message_board
      MYSQL_USER: ${MYSQL_USER:-msgboard_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-SecurePassword456!}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - message-board-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID

  app:
    build: .
    container_name: message-board-app
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://msgboard_user:SecurePassword456!@mysql:3306/message_board}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400}
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      SERVER_WORKERS: ${SERVER_WORKERS:-4}
      DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS:-10}
      DB_MIN_CONNECTIONS: ${DB_MIN_CONNECTIONS:-5}
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - message-board-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp

  nginx:
    image: nginx:alpine
    container_name: message-board-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - message-board-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run

networks:
  message-board-network:
    driver: bridge

volumes:
  mysql_data: